### ISSUE TITLE
Implement resilience: add retry for key retrieval

### ISSUE THREAD

**Issue by mhaas-work** [SAP/cloud-pysec#17]
Hello,

I believe the call to retrieve the key via HTTP could benefit from implementing a simple retry strategy. The related code is here: https://github.com/SAP/cloud-pysec/blob/daa7281c8900377e4f708d0afd460277f917a1a0/sap/xssec/key_cache.py#L66

See this link for an example implementation: https://stackoverflow.com/questions/23267409/how-to-implement-retry-mechanism-into-python-requests-library/35636367#35636367

Typically, adding a single retry will reduce transient failures immensely.

Thanks and best regards,

Michael

**Comment by firnkes** [comment]
Hi Michael,

great idea. I will implement it as soon as I find some time to do it.

Best Regards,
Patrick

**Comment by firnkes** [comment]
merged, will be part of the next release
