### ISSUE TITLE
SAP_JWT_TRUST_ACL fails at first entry

### ISSUE THREAD

**Issue by dennygee** [SAP/cloud-pysec#25]
Hi Team,

Relating to this line:
https://github.com/SAP/cloud-pysec/blob/master/sap/xssec/security_context.py#L194

I think the RunTimeError should only be raised after checking through all the acl_entry list in:
https://github.com/SAP/cloud-pysec/blob/master/sap/xssec/security_context.py#L184

The current validation fails right after checking only one entry, please help to verify if this is the right behaviour.

**Comment by strehle** [comment]
@torsten-sap  FYI 

@nenaraab  can you please check if you can handle this

**Comment by dennygee** [comment]
Hi guys, 

Like to check if there is any further updates on this, thank you!

**Comment by nenaraab** [comment]
Hi @dennygee 
Thanks for reporting.
The pull request is prepared (locally). Await permissions to contribute / release.
Best regards!

**Comment by strehle** [comment]
@dennygee please check if 2.0.9 fixes your issue, see #26

**Comment by strehle** [comment]
fixed by #26
