### ISSUE TITLE
Dependency on fixed version of six

### ISSUE THREAD

**Issue by tobias-hd** [SAP/cloud-pysec#27]
Hello colleagues,
this python package currently has a dependency on a fixed version of the python module 'six' (1.11.0), see https://github.com/SAP/cloud-pysec/blob/master/setup.py#L34. This is a quite old version (mid 2017), and when installing sap-xssec together with other packages that also require six, I run into this error message:
```
 ERROR: sap-xssec 2.0.9 has requirement six==1.11.0, but you'll have six 1.14.0 which is incompatible.
```
Do you think it is feasible for you to depend on a more recent version of six, or (even better, I think), not to depend on a fixed version (like 1.*)?

**Comment by strehle** [comment]
hi @tobias-hd , thanks for the hint.
we release a version without a fixed version.
regards,
-markus
