### ISSUE TITLE
Evaluate attribute "aud" as replacement for SAP_JWT_TRUST_ACL

### ISSUE THREAD

**Issue by nenaraab** [SAP/cloud-pysec#29]
Evaluate the JWT token element named "aud" (in favor of environment variable SAP_JWT_TRUST_ACL).

Stay with the evaluation of SAP_JWT_TRUST_ACL for the time being so that the API remains backwards compatible. This is still relevant when you get called with a token of grant type `user_token`. Of course apps that are potentially called with a user_token have to keep SAP_JWT_TRUST_ACL configuration.

Note
The evaluation of SAP_JWT_TRUST_ACL shall be removed after a grace period of 6/9 months. XSUAA team will inform you about updates.

Further References / Spec:
https://github.wdf.sap.corp/CPSecurity/Knowledge-Base/blob/master/03_ApplicationSecurity/TokenValidation.md#audience-validation

**Comment by nenaraab** [comment]
Jira BLI: https://jtrack.wdf.sap.corp/browse/SECAUTH-666

**Comment by nenaraab** [comment]
@torsten-sap is there any timeline for `user_token` deprecation?

**Comment by torsten-sap** [comment]
No, not from XSUAA server-side.

**Comment by nenaraab** [comment]
@robertofalk have you already released that feature?

**Comment by robertofalk** [comment]
closed by #34
