### ISSUE TITLE
Remove sap_py_jwt dependency 

### ISSUE THREAD

**Issue by robertofalk** [SAP/cloud-pysec#48]
Remove sap_py_jwt dependency and use only cryptography

**Comment by HamidKhanamiri** [comment]
Hi, is it possible to speed up this dependency removal, or at least change the default value of USE_SAP_PY_JWT to False.
https://github.com/SAP/cloud-pysec/blob/c5bb5d9ea7a00de57bfc2b9311c7df7503978cb5/sap/conf/config.py#L2

Thanks!
Hamid

**Comment by robertofalk** [comment]
Sure, the PR is already there, I created it last year and forgot about it completely. I asked my colleague to review and approve it.

**Comment by HamidKhanamiri** [comment]
@robertofalk Thank you for the quick reply :)
