### ISSUE TITLE
Feature request: Provide async functionality

### ISSUE THREAD

**Issue by tobias-hd** [SAP/cloud-pysec#51]
For asynchronous web frameworks like [fastAPI](https://fastapi.tiangolo.com/), [aiohttp](https://docs.aiohttp.org/en/stable/), or even async [django](https://docs.djangoproject.com/en/3.1/topics/async/#), it would be very beneficial to provide asynchronous function for token fetching and validation.

As an example, in a productive setup for an SAP application we fetch tokens with `request_token_for_client`, taking usually around 300-500ms. The server is blocked during that time, and it would be very advantageous to have an async equivalent to that functionality.

Thanks,
Tobias

**Comment by pletnes** [comment]
Seconded, blocking the server for 500 ms is very bad for performance.

**Comment by tobias-hd** [comment]
It seems to me this is solved by now with https://github.com/SAP/cloud-pysec/pull/55. Thanks!

An update of the docu in the wiki is still missing, see [request_token_for_client](https://github.com/SAP/cloud-pysec/wiki#securitycontextrequest_token_for_clientservicecredentials-scopes---str). It should just require mentioning the new function `request_token_for_client_async`, with the same interface as the existing `request_token_for_client` - only to be called with `await ...`.
@robertofalk Since it is not possible to setup a PR for a wiki, could you please take care of this?

**Comment by robertofalk** [comment]
ok, I'll do it

**Comment by robertofalk** [comment]
Done: https://github.com/SAP/cloud-pysec/wiki#securitycontextrequest_token_for_client_asyncservicecredentials-scopes---str
