### ISSUE TITLE
request for code reconfiguration

### ISSUE THREAD

**Issue by HamidKhanamiri** [SAP/cloud-pysec#60]
The class SecurityContextXSUAA needs a token and client service UAA credentials to be instantiated, https://github.com/SAP/cloud-pysec/blob/c5bb5d9ea7a00de57bfc2b9311c7df7503978cb5/sap/xssec/security_context_xsuaa.py#L76

whereas it contains methods that can be used to retrieve a token using UAA credentials, such as https://github.com/SAP/cloud-pysec/blob/c5bb5d9ea7a00de57bfc2b9311c7df7503978cb5/sap/xssec/security_context_xsuaa.py#L591 and https://github.com/SAP/cloud-pysec/blob/c5bb5d9ea7a00de57bfc2b9311c7df7503978cb5/sap/xssec/security_context_xsuaa.py#L620

So users cannot reach these methods to get a token if they don't have one already. I suggest these methods and associated (smaller) functions are moved just out of the class, or reorganised differently. As far as I understand, the mentioned methods are not being used in the token validation flow.

In my program, I insist to use the mentioned methods in the class SecurityContextXSUAA to get a token, because your code is developed and tested, and using that reduces size of my program. So currently this is my hack  to use the class to get a token (Apologies for the messed up indentation. No idea how to fix it):

> ''' modify class SecurityContextXSUAA to be able to fetch token with clinet_credentials'''
class ModifiedSapXSUAA(SecurityContextXSUAA):
    '''Use sap.xssec.security_context_xsuaa.SecurityContextXSUAA
     to get a token using client (service) uaa creds. instead of API calls'''
    def __init__(self, uaa_creds:dict, scopes=None) -> None:
        self.uaa_creds = uaa_creds
        self.scopes = scopes
    def get_token(self):
        self._token = "none"
        self._check_uaa_response = lambda *args: None
        _const_attr = getattr(constants, 'GRANTTYPE_JWT_BEARER') # jwt_bearer grant type can be used only when there is already a valid token
        setattr(constants, 'GRANTTYPE_JWT_BEARER', 'client_credentials')
        token = SecurityContextXSUAA.request_token_for_client(self, self.uaa_creds, self.scopes)
        setattr(constants, 'GRANTTYPE_JWT_BEARER', _const_attr)
        SecurityContextXSUAA(token, self.uaa_creds)
        return token

**Comment by robertofalk** [comment]
Hi @HamidKhanamiri ,

We need to check if this can be done because in the end it's a breaking change, and we just released version 4 which included a breaking change, so the best would be to find a way to develop it in a non-breaking way.

**Comment by HamidKhanamiri** [comment]
Hi @robertofalk first of all thanks for the new release. I might be the first user downloading it. I guess a non-breaking solution would be to turn token here https://github.com/SAP/cloud-pysec/blob/c5bb5d9ea7a00de57bfc2b9311c7df7503978cb5/sap/xssec/security_context_xsuaa.py#L81 to an optional arg by giving a default value (ex. token="none"), and inside the class skipping the validation functions when token="none" using a few if-else flow. Or just adding a new file or class which can be used to fetch a token prior to performing any validation.

**Comment by robertofalk** [comment]
Hi @HamidKhanamiri,
I checked internally and in fact `request_token_for_client_async` was created to request a user token, in a token exchange scenario. This library was not created to be a generic oAuth client but a oAuth token validation mainly. The reason why this method exists is because it also does on the nodeJs version of the library, which is used by the AppRouter when exchanging tokens, but since a python version of the AppRouter was never created, we never really had a use for this method.
Roberto
