### ISSUE TITLE
setup.py now has a hard dependency on requests package, fails to build

### ISSUE THREAD

**Issue by mhaas-work** [SAP/cloud-pysec#9]
Hello colleagues,

commit 889478c1101ffed29e0ceed40aa308969055bfce introduces a hard dependency on the `requests` package. Basically, the import `from sap.xssec.config import USE_SAP_PY_JWT` in setup.py executes `sap.xssec.__init__`, which will at a later point run `import requests`.

Although `setup.py` specifies a dependency on `requests`, this comes much too late as `setup.py` already executes the code for which it is supposed to pull in the dependencioes.

As a workaround, it may be sufficient to move `config.py` into its own package to avoid running `__init__.py`.

Steps to reproduce:

```
$ python3 -m venv /tmp/test
$ source /tmp/test/bin/activate
$ pip install sap-xssec
```

Output:
```
Collecting sap-xssec
  Downloading https://files.pythonhosted.org/packages/c0/b5/336fde783611000bc8d257466348d10900438b83389fa7c5dfc3b868e057/sap_xssec-2.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_j/hnv2m0816dj2rr3bq7nxz92r0000gn/T/pip-install-za01cpf8/sap-xssec/setup.py", line 5, in <module>
        from sap.xssec.config import USE_SAP_PY_JWT
      File "/private/var/folders/_j/hnv2m0816dj2rr3bq7nxz92r0000gn/T/pip-install-za01cpf8/sap-xssec/sap/xssec/__init__.py", line 3, in <module>
        from sap.xssec.security_context import SecurityContext
      File "/private/var/folders/_j/hnv2m0816dj2rr3bq7nxz92r0000gn/T/pip-install-za01cpf8/sap-xssec/sap/xssec/security_context.py", line 7, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'
```

**Comment by strehle** [comment]
requests is only available 2.21.0 for python3, sorry for this
Please install latest requests and then sap_xssec should work

**Comment by strehle** [comment]
see https://github.com/SAP/cloud-pysec/releases/tag/2.0.4 , should solve it

**Comment by mhaas-work** [comment]
Thank you very much! Works beautifully now.
